### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by fourq** [JWally/jsLPSolver#26]
If I have 10 players, and each player has variables, how can get the top 5 players that meet the constraints?

```js
var model = {
      optimize: 'salary',
      opType: 'max',
      constraints: {
        salary: {max: 50000}
      },
      variables: {
        p0: {weight: 10, salary: 1000},
        p1: {weight: 20, salary: 2000},
        p2: {weight: 30, salary: 3000},
        p3: {weight: 40, salary: 4000},
        p4: {weight: 50, salary: 5000},
        p5: {weight: 60, salary: 6000},
        p6: {weight: 70, salary: 7000},
        p7: {weight: 80, salary: 8000},
        p8: {weight: 90, salary: 9000},
        p9: {weight: 100, salary: 10000}
      }
    };
```

**Comment by fourq** [comment]
Would I do something like this?

```js
var model = {
      optimize: 'salary',
      opType: 'max',
      constraints: {
        salary: {max: 50000},
        size: {max: 5}
      },
      variables: {
        p0: {weight: 10, salary: 1000, size: 1},
        p1: {weight: 20, salary: 2000, size: 1},
        p2: {weight: 30, salary: 3000, size: 1},
        p3: {weight: 40, salary: 4000, size: 1},
        p4: {weight: 50, salary: 5000, size: 1},
        p5: {weight: 60, salary: 6000, size: 1},
        p6: {weight: 70, salary: 7000, size: 1},
        p7: {weight: 80, salary: 8000, size: 1},
        p8: {weight: 90, salary: 9000, size: 1},
        p9: {weight: 100, salary: 10000, size: 1}
      }
    };
```

**Comment by bchevalier** [comment]
Hello,

It looks like the problem you are trying to model is a [knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem). If you wanted to make the optimal lineup for a fantasy football game, I am not sure this is the best approach because it will take quite some time for the solver to find the optimal solution. But let's try anyway.

Your requirements are:
- Each player can be picked is 1. A player can be either selected or not selected, it cannot be 50% selected, therefore you have to state that your variables are integers.
- You want a minimum and a maximum of 5 players to be selected. Therefore you want exactly 5 players to be selected.
- I imagine you do not want to optimize the salary, instead you want to optimize the total value of the lineup.

The model becomes the following one:
```
var model = {
      optimize: 'value',
      opType: 'max',
      constraints: {
        salary: {max: 50000},
        maxSelection: {equal: 5},
        selection0: {max: 1},
        selection1: {max: 1},
        selection2: {max: 1},
        selection3: {max: 1},
        selection4: {max: 1},
        selection5: {max: 1},
        selection6: {max: 1},
        selection7: {max: 1},
        selection8: {max: 1},
        selection9: {max: 1}
      },
      variables: {
        p0: {value: 10, salary: 1000, selection0: 1, maxSelection: 1},
        p1: {value: 20, salary: 2000, selection1: 1, maxSelection: 1},
        p2: {value: 30, salary: 3000, selection2: 1, maxSelection: 1},
        p3: {value: 40, salary: 4000, selection3: 1, maxSelection: 1},
        p4: {value: 50, salary: 5000, selection4: 1, maxSelection: 1},
        p5: {value: 60, salary: 6000, selection5: 1, maxSelection: 1},
        p6: {value: 70, salary: 7000, selection6: 1, maxSelection: 1},
        p7: {value: 80, salary: 8000, selection7: 1, maxSelection: 1},
        p8: {value: 90, salary: 9000, selection8: 1, maxSelection: 1},
        p9: {value: 100, salary: 10000, selection9: 1, maxSelection: 1}
      },
     ints: {
       p0: 1, p1: 1, p2: 1, p3: 1, p4: 1, p5: 1, p6: 1, p7: 1, p8: 1, p9: 1
     }
    };
```

**Comment by bchevalier** [comment]
Now, if you wanted to select only one quarterback, what you could do is:

```javascript
var model = {
      optimize: 'value',
      opType: 'max',
      constraints: {
        salary: {max: 50000},
        nbPlayers: {equal: 5},
        nbQB: {equal: 1},
        selection0: {max: 1},
        selection1: {max: 1},
        selection2: {max: 1},
        selection3: {max: 1},
        selection4: {max: 1},
        selection5: {max: 1},
        selection6: {max: 1},
        selection7: {max: 1},
        selection8: {max: 1},
        selection9: {max: 1}
      },
      variables: {
        p0: {value: 10, salary: 1000, selection0: 1, nbPlayers: 1, nbQB: 1}, // this is a quarter-back
        p1: {value: 20, salary: 2000, selection1: 1, nbPlayers: 1, nbQB: 1}, // this is a quarter-back
        p2: {value: 30, salary: 3000, selection2: 1, nbPlayers: 1},
        p3: {value: 40, salary: 4000, selection3: 1, nbPlayers: 1},
        p4: {value: 50, salary: 5000, selection4: 1, nbPlayers: 1},
        p5: {value: 60, salary: 6000, selection5: 1, nbPlayers: 1},
        p6: {value: 70, salary: 7000, selection6: 1, nbPlayers: 1},
        p7: {value: 80, salary: 8000, selection7: 1, nbPlayers: 1},
        p8: {value: 90, salary: 9000, selection8: 1, nbPlayers: 1},
        p9: {value: 100, salary: 10000, selection9: 1, nbPlayers: 1}
      },
     ints: {
       p0: 1, p1: 1, p2: 1, p3: 1, p4: 1, p5: 1, p6: 1, p7: 1, p8: 1, p9: 1
     }
    };
```

If you apply this logic with every position (DST, TE, RB, WR, FLEX), you can get rid of the ```nbPlayers``` constraint. You would obtain:


```javascript
var model = {
      optimize: 'value',
      opType: 'max',
      constraints: {
        salary: {max: 50000},
        nbQB: {equal: 1},
        nbWR: {equal: 3},
        nbRB: {equal: 2},
        nbTE: {equal: 1},
        nbFLEX: {equal: 1},
        nbDST: {equal: 1},
        selection0: {max: 1},
        selection1: {max: 1},
        selection2: {max: 1},
        selection3: {max: 1},
        selection4: {max: 1},
        selection5: {max: 1},
        selection6: {max: 1},
        selection7: {max: 1},
        selection8: {max: 1},
        selection9: {max: 1}
      },
      variables: {
        p0: { value: 10, salary: 1000, selection0: 1, nbQB: 1 }, // quarter-back
        p1: { value: 20, salary: 2000, selection1: 1, nbQB: 1 }, // quarter-back
        p2: { value: 30, salary: 3000, selection2: 1, nbWR: 1, nbFLEX: 1 }, // wide-receiver
        p3: { value: 40, salary: 4000, selection3: 1, nbWR: 1, nbFLEX: 1 }, // wide-receiver
        p4: { value: 50, salary: 5000, selection4: 1, nbWR: 1, nbFLEX: 1 }, // wide-receiver
        p5: { value: 60, salary: 6000, selection5: 1, nbRB: 1, nbFLEX: 1 }, // running-back
        p6: { value: 70, salary: 7000, selection6: 1, nbRB: 1, nbFLEX: 1 }, // running-back
        p7: { value: 80, salary: 8000, selection7: 1, nbTE: 1, nbFLEX: 1 }, // tight-end
        p8: { value: 90, salary: 9000, selection8: 1, nbTE: 1, nbFLEX: 1 }, // tight-end
        p9: { value: 100, salary: 10000, selection9: 1, nbDST: 1 } // defense
      },
     ints: {
       p0: 1, p1: 1, p2: 1, p3: 1, p4: 1, p5: 1, p6: 1, p7: 1, p8: 1, p9: 1
     }
    };
```

To complete the model you would just need to add all the players with their correct values and salaries and you should be good to go. Let me know how it goes in terms of execution time. If it takes too long, you can give us an example of your model so that we can try to implement something to speed up the process.

**Comment by fourq** [comment]
Thanks a ton for taking the time to explain and give examples. I will follow up, hopefully, this afternoon. :+1:

**Comment by fourq** [comment]
Here's what I've generated so far: https://gist.github.com/fourq/2047935c4e52b317350a (it's huge!), but it's throwing on `solve()`:

Error:
```sh
Unhandled rejection TypeError: Cannot read property 'cuts' of null
    at MILP (/Users/fourq/src/kenny-rogers/node_modules/javascript-lp-solver/src/MILP.js:186:41)
    at Model.solve (/Users/fourq/src/kenny-rogers/node_modules/javascript-lp-solver/src/Model.js:329:16)
    at Solve (/Users/fourq/src/kenny-rogers/node_modules/javascript-lp-solver/src/main.js:74:30)
    at Object.module.exports.NBA.contests [as NBA] (/Users/fourq/src/kenny-rogers/lib/providers/draftkings/optimize.js:109:19)
    at /Users/fourq/src/kenny-rogers/lib/providers/draftkings/index.js:77:23
    at tryCatcher (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:615:18)
    at Promise._resolveCallback (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:416:57)
    at Promise._settlePromiseFromHandler (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:502:17)
    at Promise._settlePromise (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:615:18)
    at Promise._resolveCallback (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:416:57)
    at Promise._settlePromiseFromHandler (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:502:17)
    at Promise._settlePromise (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:615:18)
    at MappingPromiseArray.PromiseArray._resolve (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise_array.js:125:19)
    at MappingPromiseArray._promiseFulfilled (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/map.js:97:18)
    at Promise._settlePromise (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:551:26)
    at Promise._settlePromise0 (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:615:18)
    at PropertiesPromiseArray.PromiseArray._resolve (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PropertiesPromiseArray._promiseFulfilled (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/props.js:78:14)
    at Promise._settlePromise (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:551:26)
    at Promise._settlePromise0 (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/promise.js:674:18)
    at Async._drainQueue (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/fourq/src/kenny-rogers/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

Where "G" = [one of "SG"|"PG"], and "F" = [one of "SF"|"PF"] and "UTIL" = [one of "PG"|"SG"|"SF"|"PF"|"C"]

**Comment by bchevalier** [comment]
I found at least one issue with the model. The following part:
```json
"UTIL":{
   "equal":1
},
"selection35":1,
"SF":{
   "equal":1
},
"F":{
   "equal":1
}
```
Should be:
```json
"UTIL": 1,
"selection35":1,
"SF":1,
"F": 1,
```

**Comment by fourq** [comment]
ah!, ok. ty. I'll fix now

**Comment by fourq** [comment]
I updated the script to produce: https://gist.github.com/fourq/2047935c4e52b317350a but I'm still getting the same error.

**Comment by bchevalier** [comment]
So I investigated and there is a bug in the solver but your problem in infeasible (solving should work if the problem was feasible). You have a constraint that specify that UTIL should be equal to 1 but it contradicts other the constraints C G and F equal 1.

**Comment by fourq** [comment]
Does that mean changing my constraints to the following should work?

```json
    constraints: {
        s: {max: 50000},
        PG: {equal: 1},
        SG: {equal: 1},
        SF: {equal: 1},
        PF: {equal: 1},
        C: {equal: 1},
        G: {equal: 1},
        F: {equal: 1},
        UTIL: {equal: 1}
      }
```

**Comment by bchevalier** [comment]
I just made a [PR](https://github.com/JWally/jsLPSolver/pull/28) that would avoid the crashing. So it's just a question of time before it gets merged.

About your model, the issue is that you made an impossible problem. I imagine that somewhere there is something that looks like this:
```javascript
selection1 + selection2 = 1 (constraint C)
selection2 + selection3 = 1 (constraint G)
selection1 + selection3 = 1 (constraint UTIL)
```

If selection1 is set to 1, then selection2 has to be 0 (due to constraint C) and selection3 has to be 1 (due to constraint G). You get a contradiction because selection1 and selection3 cannot both be equal to 1 since it violates constraint UTIL.
If selection1 is set to 0, then selection2 has to be 1 (due to constraint C) and selection3 has to be 0 (due to constraint G). You get a contradiction because selection1 and selection3 cannot both be equal to 0 since it violates constraint UTIL.

**Comment by JWally** [comment]
Sorry if I dropped the ball on this one :-O
Is this ok to close?

**Comment by fourq** [comment]
ty
